name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  success:
    name: Success
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - run: exit 0

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [success]
    if: github.event_name == 'push'
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Setup git user
        run: |
          git config --global user.email "176291722+changeset-bot-release-bot[bot]@users.noreply.github.com"
          git config --global user.name "changeset-bot-release-bot[bot]"

      - run: npm run build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          title: New Release
          commit: Create new release
          publish: npm run release
          setupGitUser: false
